### ISSUE TITLE
G2/M subtasks, questions for experts

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1049]
![g2_m](https://cloud.githubusercontent.com/assets/7359272/18472451/7f2fbbfc-79af-11e6-8255-9886d05347cf.jpg)

Key
blue circle = kinase
Blue circle /red bar = inhibitory kinase
Blue circle green arror = activatory kinase
yellow circle= phosphatase
yellow circle green arrow= activatory phosphatase
+ve or -ve on 'edge' affect on G2/M transition
solid circles around gene products 'essential'
broken circles around gene products 'non-essntial'

**Comment by ValWood** [comment]
- [ ] To me, it would make the most sense to define the regulation of the G2/M transition as a 'signalling network'

To do this we would need to exclude checkpoint proteins upstream of the sensors (ATR/ATM)

We could do this by moving the relationship between the checkpoint term and the negative regulation of the transition, and MOVE the relationship  so that ONLY the "signal transduction involved in yada yada checkpoint" was part of the "negative regulation of x transition"

This would make detection of the stimulus for activating the checkpoint outside of the regulation of the transition (causally upstream of, rather than involved in)

![change rel](https://cloud.githubusercontent.com/assets/7359272/18471169/7d1688ca-79a8-11e6-8f08-4595e3727fd9.jpg)

**Comment by ValWood** [comment]
- [ ] orc1 is annotated to GO:0033314 based on an orc1 cdc18 double mutant phenotype in PMID:11988741 (updated from and IMP in Artemis, I think). I stashed a bit of email about it - basically, the checkpoint isn't working properly in the double mutant. I have no strong feelings about whether to keep the GO annotation or just the phenotypes.

session f655c12afd36086c

**Comment by ValWood** [comment]
- [ ] ppa2 feeds into this network, but how?....do we know any substrates? I haven't been able to find any and only one ppa2 paper left....

**Comment by ValWood** [comment]
- [ ] cdc2-3w encodes p34cdc2, whose Y15 is dephosphorylated in a Cdc25-indepen- dent manner. (How does this happen? )

**Comment by ValWood** [comment]
- [ ] What is the mechanism of cdc25 increasing the activity of cdc2 by de-phopshorylation.  Doe the phosphorylation of cdc2 *directly* effect cdc2 activity?

**Comment by ValWood** [comment]
AI
-[ ] wis4 & win1 upstream of wis1

-[ ] rad24 and chk1 are viable

**Comment by ValWood** [comment]
- [ ] SCF inhibits (degrades) wee1, but is this after the G2/M transition?

**Comment by ValWood** [comment]
- [ ] suc1 does not have a mitotic cell cycle regulation annotation

**Comment by ValWood** [comment]
- [ ] when does mcs6 - phosphorylate cdc2?

**Comment by ValWood** [comment]
- [ ] how does cdc2 link to polo?

**Comment by ValWood** [comment]
current

![g2_m](https://cloud.githubusercontent.com/assets/7359272/21467859/5202fd8a-c9f3-11e6-9ac0-612aa7b53b55.jpg)

**Comment by ValWood** [comment]
completed tasks from this ticket:
- [x] wis4 & win1 upstream of wis1

**Comment by ValWood** [comment]
- [ ]  This activation involves P of cdc25 by cdc2 (hoffman 1993, Izumi 113,1995)
(feedback loop)

**Comment by ValWood** [comment]
how do these connect to cdc2?
- [ ] plo1
- [ ] fin1 (nima)

**Comment by ValWood** [comment]
- [ ]  check  https://www.pombase.org/reference/PMID:22451489
with Jacky, and ask about nucleoporins

**Comment by ValWood** [comment]
Outstanding covered by
https://github.com/pombase/curation/issues/2900
