### ISSUE TITLE
Mondo checking

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2700]
Name	Term	Genes
- [x] amyloidosis (disease)	MONDO:0019065	1 (seems low but mapping identically)
- [x] anemia (disease)	MONDO:0002280	86 4 fewr, most caused by https://github.com/monarch-initiative/mondo/issues/1503
- [x] autosomal dominant disease	MONDO:0000426	117 https://github.com/monarch-initiative/mondo/issues/1488
- [x] autosomal recessive disease	MONDO:0006025	205 https://github.com/monarch-initiative/mondo/issues/1488
- [x] bone development disease	MONDO:0005497	116
- [x] cancer	MONDO:0004992	188 https://github.com/monarch-initiative/mondo/issues/1506
- [x] carbohydrate metabolism disease	MONDO:0037792	113 (increased from 6, some odd inferences reported)
- [x] cerebral degeneration	MONDO:0024238	0 https://github.com/monarch-initiative/mondo/issues/1486
- [x] cognitive disorder	MONDO:0002039	9
- [x] dystonic disorder	MONDO:0003441	15
- [x] epilepsy	MONDO:0005027	181
- [x] eye disease	MONDO:0005328	281 https://github.com/monarch-initiative/mondo/issues/1482
- [x]  heart disease	MONDO:0005267	80
hepatobiliary disease	MONDO:0002515	29
immune system disease	MONDO:0005046	111
- [x] inborn disorder of purine or pyrimidine metabolism	MONDO:0019254	158 https://github.com/monarch-initiative/mondo/issues/1484
- [x] inborn mitochondrial metabolism disorder	MONDO:0004069	146 https://github.com/monarch-initiative/mondo/issues/1485
- [x] inherited amino acid metabolic disorder	MONDO:0004736	57 https://github.com/monarch-initiative/mondo/issues/1493 & https://github.com/monarch-initiative/mondo/issues/1492
- [x] inherited lipid metabolism disorder	MONDO:0002525	90
- [x]  inherited porphyria	MONDO:0019142	8
kidney disease	MONDO:0005240	122
- [x]  lysosomal storage disease	MONDO:0002561	33
- [x] monogenic disease	MONDO:0000275	378 https://github.com/monarch-initiative/mondo/issues/1495
- [x] myopathy	MONDO:0005336	98
neurodegenerative disease	MONDO:0005559	153
- [x] nonsyndromic genetic deafness	MONDO:0019497	39
paraplegia	MONDO:0003757	27
peripheral neuropathy	MONDO:0005244	191
- [x]  peroxisomal disease	MONDO:0019053	14
skin disease	MONDO:0005093	154

**Comment by ValWood** [comment]
For reference

<img width="1040" alt="disease_slim_comparison" src="https://user-images.githubusercontent.com/7359272/81586050-e989c680-93ac-11ea-8d54-5ba00c63fe05.png">

**Comment by ValWood** [comment]
@Antonialock

**Comment by ValWood** [comment]
Will keep this open, but no action for us  here
