### ISSUE TITLE
checklist for Duncan & Mata riboseq paper PMID: 24929437

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#863]
- [x]  Misannotated genes (supp table 4a)
- [ ]  alternative intron retention (supp table 4d)
- [x]  11 ‘dubious appeared to be translated (did we change these to coding?)
- [x]  3 dubious were translated in different frames - were these updated??
- [ ]  35 dubious probably ncRNA (add confirmation) (Omitting this as should become clear)
- [ ]  spac3c7.15c early meiosis, gene overlapping, late meiosis
- [ ]  nup184 will change when sequence updated
- [ ]  715 translated orfs
- [ ]  46 new translated genes 39 new orfs (>45 codons) (15 novel non overlapping, 14 nested, does not add up)
8. 2 extensions to 5’ leaders
9.  24% /1571 of ncRNAs produce short peptides The prl46 RNA.557, RNA.1597 had conserved orfs
   12.uORFs 1735 uORFS in 1272 genes
10. SPCC1235.01 uORF 347 codns
11. SPAC11D3.13 uorf
12. SPAC6G9.05 uorf

**Comment by ValWood** [comment]
3. My notes said this was done, but it didn't seem to be.

SPAC3G6.07 updated to orphan (conserved in Schizos) DONE
SPAC959.11 updated to orphan (conserved in Schizos) DONE
SPBC13G1.16 updated to orphan (conserved in Schizos) DONE
SPBC15D4.08c updated to orphan (conserved in Schizos) DONE
SPBC1685.17 warning, translated non-conserved orf in low complexity region (ALREADY DONE)
SPBC30B4.09 updated to orphan (conserved in Schizos) ALREADY DONE
SPCC622.01c DONE
SPCC622.02 DONE
SPCC622.04 DONE
SPCC622.07 DONE
SPCC794.15 updated to orphan (conserved in Schizos)  (DONE)

**Comment by ValWood** [comment]
I Misannotated genes (supp table 4a)

Now done

**Comment by ValWood** [comment]
II alternative intron retention (supp table 4d)
tranferred to
https://github.com/pombase/curation/issues/61

**Comment by ValWood** [comment]
IV 3 dubious were translated in different frames - were these updated??

This was done as part of 3.

**Comment by ValWood** [comment]
Questions sent to Juan

- [ ] 1. 
Could you supply a GFF file  (Or 2) of the uORFs in ncRNAs and the uORFs in protein coding genes.
The instructions  for the file format  specification is here: http://www.pombase.org/faqs/what-gff3
and a link to the validator is here:
You can use uORF in column x as this is a valid SO term
http://www.sequenceontology.org/browser/current_svn/term/SO:0002027
We will display this as a browser track(s), and announce on the release which it is included.

- [ ] 2.
" Of the remaining 6, 2 appeared to be extensions to annotated 5′ leaders, 3 were present in the 3′-UTRs of highly translated genes (possibly reflecting leaky termination of translation) and one was located downstream of the nup184 gene (discussed above). "

- [ ] .  3. Do I need to update the 2 gene structures associated with  5' leaders ?
I can't see which these are from the paper.

- [ ] 4.  Examination of the corresponding mRNA data suggested that 39 of them (85%) were transcribed as independent units ....
.....15 translated ORFs did not overlap with annotated coding sequences (in either strand). Their sequences were generally not conserved, but one of them displayed homology to the N-terminal part of a protein present in multiple copies in S. cryophilus and S. octosporus. 
Surprisingly, we found 14 cases in which the newly-discovered translated ORF were antisense to an annotated coding sequence (completely overlapping in 10 cases, and more than 80% in the other 4).
This comes to 29 not 39, are there 10 more?

**Comment by ValWood** [comment]
I also have a folder in  "a in progress" need to check that I did everything in here too

**Comment by ValWood** [comment]
out of date
